name: Release Build

on:
  push:
    branches:
      - develop
      - master
      - main
      - release/**
      - hotfix/**
  pull_request:
    branches:
      - develop
      - main
      - release/**
      - hotfix/**

jobs:
  codestyle-php:
    name: PHP Code Style
    runs-on: ubuntu-latest
    container:
      image: mrdollar4444/plus-wp-builder-wpbakery:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Composer dependencies
        run: php ci/composer.phar install

      - name: Check PHP Code Style
        run: php vendor/bin/phpcs --standard=ci/phpcs.xml .
  compatibility-php:
    name: PHP Code Compatibility
    runs-on: ubuntu-latest
    container:
      image: mrdollar4444/plus-wp-builder-wpbakery:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Composer dependencies
        run: php ci/composer.phar install

      - name: Check PHP Compatibility
        run: php vendor/bin/phpcs --standard=PHPCompatibility --extensions=php --runtime-set testVersion 5.6-8.4 --ignore=vendor/* .
  php-clones:
    name: PHP Clone Detection
    runs-on: ubuntu-latest
    container:
      image: mrdollar4444/plus-wp-builder-wpbakery:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: PHP Clone Detection
        run: php ci/phpcpd.phar --fuzzy .

  php-stan-statanalize:
    name: PHP Stan Statanalize
    runs-on: ubuntu-latest
    container:
      image: mrdollar4444/plus-wp-builder-wpbakery:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Composer dependencies
        run: php ci/composer.phar install

      - name: PHP Static Analysis
        run: cp -r  /__w/plus-wp-builder-wpbakery-timeline-element /var/www/html/wp-content/plugins; cd /var/www/html; wp plugin activate plus-wp-builder-wpbakery-timeline-element --allow-root; cd wp-content/plus-wp-builder-wpbakery-timeline-element/ci; ../vendor/bin/phpstan analyze 